## Import packages

In [24]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import scipy.io as scio
import os
import mne
import pickle

# from numba import jit, cuda

import pac
import scipy.signal as ss

import Get_global_local_feature

## Get global feature using convolution

In [25]:
PAC_dist = np.ones(shape=[20,20])
PAC_dist[0:5,0:5] = PAC_dist[0:5,0:5]*2
PAC_dist[5:10,5:10] *= 3
PAC_dist[10:15,10:15]*= 0
PAC_dist[15:20,15:20]*= 10
Get_global_local_feature.conv_PAC_dist(PAC_dist)
# # Filtering
# width_filter = 5
# height_filter = 5
# kernel_filter = np.ones(shape=[width_filter,height_filter])/(width_filter*height_filter)
# PAC_feature = ss.convolve2d(PAC_dist,kernel_filter,mode='valid')
# PAC_feature.shape
# # Sampling
# height_index = np.linspace(0,PAC_feature.shape[0]-1,PAC_dist.shape[0]//height_filter).astype(np.int32)
# width_index = np.linspace(0,PAC_feature.shape[0]-1,PAC_dist.shape[1]//width_filter).astype(np.int32)
# h,w = np.meshgrid(height_index,width_index)
# PAC_feature[h,w]

array([[ 2.,  1.,  1.,  1.],
       [ 1.,  3.,  1.,  1.],
       [ 1.,  1.,  0.,  1.],
       [ 1.,  1.,  1., 10.]])

In [26]:
a = np.ones([3,3])
a[1,1] = 15
print(a)

u,v = np.meshgrid([1],[0,1,2])
print(u)
a[u,v]



[[ 1.  1.  1.]
 [ 1. 15.  1.]
 [ 1.  1.  1.]]
[[1]
 [1]
 [1]]


array([[ 1.],
       [15.],
       [ 1.]])

In [33]:
def conv_PAC_dist(PAC_dist,h=4,w=4,down_sample_factor_h=4,down_sample_factor_w=4,filter_mode='valid'):
    """PAC_dist input PAC values\
    h filter kernel size along axis 0\
    w filter kernel size along axis 1\
    down sample factor h along axis 0\
    down sample factor w along axis 1\
    filter mode define the mode of convolve2d of scipy.signal"""
    # Filtering
    width_filter = w
    height_filter = h
    kernel_filter = np.ones(shape=[width_filter,height_filter])/(width_filter*height_filter)
    PAC_feature = ss.convolve2d(PAC_dist,kernel_filter,mode=filter_mode)

    # Sampling
    height_index = np.linspace(0,PAC_feature.shape[0]-1,PAC_dist.shape[0]//down_sample_factor_h).astype(np.int32)
    width_index = np.linspace(0,PAC_feature.shape[0]-1,PAC_dist.shape[1]//down_sample_factor_w).astype(np.int32)
    h,w = np.meshgrid(height_index,width_index)
    return PAC_feature[w,h]


In [34]:
a = np.array( [[1]*5 + [2]*5]*5 + [[3]*5 + [4]*5]*5 )

In [35]:
conv_PAC_dist(a)

array([[1., 2.],
       [3., 4.]])